name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-west-2
  ECR_REPOSITORY: bluegreen-demo-repo
  ECS_SERVICE: demo-service
  ECS_CLUSTER: demo-cluster
  CONTAINER_NAME: app-container
  CODEDEPLOY_APP: bluegreen-demo-app
  CODEDEPLOY_GROUP: bluegreen-demo-dg

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for AWS OIDC
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # AWS login
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        # IAM role that created in main.tf
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionRole
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Build and Push Docker image
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }} # for better traceability
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    # Security scanning
    - name: Trivy Vulnerability Scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ steps.build-image.outputs.image }}
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'

    # Change ACCOUNT_ID placeholder with real ID
    - name: Update Account ID in Task Definition
      run: |
        sed -i "s|<ACCOUNT_ID>|${{ secrets.AWS_ACCOUNT_ID }}|g" task-definition.json

    # Creating new task definition (update image ID)
    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}

    # Deploy, saves new task definition file to AWS ECS
    # Then reads appspec.yaml
    # Then triggers CodeDeploy service 
    - name: Deploy to Amazon ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true # pipeline waits untill CodeDeploy process finishes
        codedeploy-appspec: appspec.yaml
        codedeploy-application: ${{ env.CODEDEPLOY_APP }}
        codedeploy-deployment-group: ${{ env.CODEDEPLOY_GROUP }}